name: intiface_central
description: Intiface Central

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.6.0
  flutter_local_notifications: ^11.0.0
  path_provider: ^2.0.11
  path: ^1.8.1
  window_manager: ^0.2.5
  web_socket_channel: ^2.2.0
  network_info_plus: ^2.1.4+1
  permission_handler: ^10.0.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  settings_ui: ^2.0.2
  flutter_markdown: ^0.6.10+5
  loggy: ^2.0.1+1
  flutter_loggy: ^2.0.1
  github: ^9.4.0
  markdown: ^6.0.1
  intiface_engine_flutter_plugin:
    path: ../intiface_engine_flutter_plugin/

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
