[package]
name = "intiface_engine_flutter_bridge"
version = "1.0.5"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Rust-Flutter bridge for IntifaceEngine" 
license = "BSD-3-Clause"
homepage = "http://intiface.com"
readme = "README.md"
edition = "2021"
exclude = [".vscode/**"]

[dependencies]
intiface-engine = "1.4.2"
# intiface-engine = { path = "../../intiface-engine" }
# THIS MUST ALWAYS MATCH THE VERSION USED BY INTIFACE ENGINE
# buttplug = { path = "../../buttplug/buttplug" }
buttplug = "7.1.2"
flutter_rust_bridge = "1.79.0"
log = "0.4.19"
lazy_static = "1.4.0"
once_cell = "1.18.0"
tokio = { version = "1.29.1", features = ["rt-multi-thread", "tracing"] }
anyhow = "1.0.71"
# THIS VERSION ABSOLUTELY, POSITIVELY MUST MATCH WHATEVER BUTTPLUG LINKS, OTHERWISE THERE WILL BE
# STATIC MISALIGNMENT AND YOU DO NOT WANT TO SPEND ANOTHER 3 DAYS DEBUGGING THAT.
# btleplug = { path = "../../btleplug" }
btleplug = "0.11.0"
thiserror = "1.0.43"
getset = "0.1.2"
serde = "1.0.170"
serde_json = "1.0.100"
async-trait = "0.1.71"
futures = "0.3.28"
tracing = "0.1.37"
tracing-futures = "0.2.5"

[target.'cfg(target_os = "android")'.dependencies]
# THESE VERSIONS ABSOLUTELY, POSITIVELY MUST MATCH WHATEVER BUTTPLUG LINKS, OTHERWISE THERE WILL BE
# STATIC MISALIGNMENT AND YOU DO NOT WANT TO SPEND ANOTHER 3 DAYS DEBUGGING THAT.
jni = "0.19.0"
jni-utils = "0.1.1"
openssl-sys = {version = "0.9.90", features=["vendored"]}

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.78.0"
