[package]
name = "intiface_engine_flutter_bridge"
version = "1.0.3"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Rust-Flutter bridge for IntifaceEngine" 
license = "BSD-3-Clause"
homepage = "http://intiface.com"
readme = "README.md"
edition = "2021"
exclude = [".vscode/**"]

[dependencies]
intiface-engine = { version = "1.3.0" }
# intiface-engine = { path = "../../intiface-engine" }
flutter_rust_bridge = "1.64.0"
log = "0.4.17"
lazy_static = "1.4.0"
once_cell = "1.17.1"
tokio = { version = "1.25.0", features = ["rt-multi-thread", "tracing"] }
anyhow = "1.0.69"
# THIS VERSION ABSOLUTELY, POSITIVELY MUST MATCH WHATEVER BUTTPLUG LINKS, OTHERWISE THERE WILL BE
# STATIC MISALIGNMENT AND YOU DO NOT WANT TO SPEND ANOTHER 3 DAYS DEBUGGING THAT.
# btleplug = { path = "../../btleplug" }
btleplug = "0.10.4"
thiserror = "1.0.38"
getset = "0.1.2"
serde = "1.0.152"
serde_json = "1.0.93"
async-trait = "0.1.64"
futures = "0.3.26"
tracing = "0.1.37"
tracing-futures = "0.2.5"

[target.'cfg(target_os = "android")'.dependencies]
# THESE VERSIONS ABSOLUTELY, POSITIVELY MUST MATCH WHATEVER BUTTPLUG LINKS, OTHERWISE THERE WILL BE
# STATIC MISALIGNMENT AND YOU DO NOT WANT TO SPEND ANOTHER 3 DAYS DEBUGGING THAT.
jni = "0.19.0"
jni-utils = "0.1.0"
openssl-sys = {version = "0.9.80", features=["vendored"]}

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.64.0"
