name: intiface_engine_flutter_plugin
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2
  flutter_rust_bridge: ^1.45.0
  freezed_annotation: ^2.1.0
  ffi: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  ffigen: ^6.1.2

flutter:
  plugin:
    platforms:
      android:
        package: com.nonpolynomial.IntifaceEngineFlutterPlugin
        pluginClass: IntifaceEngineFlutterPlugin
      ios:
        pluginClass: IntifaceEngineFlutterPlugin
      windows:
        pluginClass: IntifaceEngineFlutterPlugin
