name: Intiface Central Build

# Only build on master pushes for now, otherwise we'll eat CI.
on: 
  push:
    branches:
      - master

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      - run: flutter config --enable-windows-desktop
        name: flutter config
      - run: flutter build windows --release
        name: flutter build
      - name: Restore signing pfx
        id: create-pfx
        shell: pwsh
        env:
          PFX_CONTENT: ${{ secrets.NPLABS_WINDOWS_20210514_SIGNING_CERT }} 
        run: |
          $pfxPath = Join-Path -Path $env:RUNNER_TEMP -ChildPath "cert.pfx"; 
          $encodedBytes = [System.Convert]::FromBase64String($env:PFX_CONTENT); 
          Set-Content $pfxPath -Value $encodedBytes -AsByteStream;
          Write-Output "::set-output name=PFX_PATH::$pfxPath";
      - name: Build MSIX
        shell: pwsh
        env:
          PFX_KEY: ${{ secrets.NPLABS_WINDOWS_20210514_SIGNING_KEY }} 
        run: |
          $pfxPath = Join-Path -Path $env:RUNNER_TEMP -ChildPath "cert.pfx"; 
          flutter pub run msix:create -c $pfxPath -p "$env:PFX_KEY"
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-msix
          path: |
            build/windows/runner/Release/*.msix
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
         sudo apt-get update -y
         sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
        name: flutter config
      - run: flutter build linux --release
        name: flutter build
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter config --enable-macos-desktop
        name: flutter config
      - run: flutter build macos --release
        name: flutter build
